# Library
- Numpy
- Pandas

In [ ]:
# Numpy
# numerical python

In [ ]:
# various built in function to perform numerical operation
# provices a multi dimensional array called numpy array

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
l1= [1,2,3,4]
l1

[1, 2, 3, 4]

In [ ]:
l1 = [[1,2,3,4],[5,6,7,8]]
l1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
l1*2

[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr1 = np.array([1,2,3,4])
type(arr1)

numpy.ndarray

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
arr1*2

array([2, 4, 6, 8])

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
arr2 = np.array(l1)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# attributes
arr2.size

8

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr2.ndim

2

| Data type	 | Description |
|-------------|-------------|
| `bool_`     | Boolean (True or False) stored as a byte |
| `int_`      | Default integer type (same as C `long`; normally either `int64` or `int32`)|
| `intc`      | Identical to C `int` (normally `int32` or `int64`)|
| `intp`      | Integer used for indexing (same as C `ssize_t`; normally either `int32` or `int64`)|
| `int8`      | Byte (–128 to 127)|
| `int16`     | Integer (–32768 to 32767)|
| `int32`     | Integer (–2147483648 to 2147483647)|
| `int64`     | Integer (–9223372036854775808 to 9223372036854775807)|
| `uint8`     | Unsigned integer (0 to 255)|
| `uint16`    | Unsigned integer (0 to 65535)|
| `uint32`    | Unsigned integer (0 to 4294967295)|
| `uint64`    | Unsigned integer (0 to 18446744073709551615)|
| `float_`    | Shorthand for `float64`|
| `float16`   | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa|
| `float32`   | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa|
| `float64`   | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa|
| `complex_`  | Shorthand for `complex128`|
| `complex64` | Complex number, represented by two 32-bit floats|
| `complex128`| Complex number, represented by two 64-bit floats|

In [ ]:
arr1 = np.array([1,2,3,4], dtype=np.int8)
type(arr1)

numpy.ndarray

In [ ]:
arr1

array([1, 2, 3, 4], dtype=int8)

In [ ]:
arr1.itemsize

1

In [ ]:
arr1 = np.array([1,2,3,4], dtype=np.int64)
arr1.itemsize

8

### Array Creation Routines & Mathematical functions

https://numpy.org/doc/stable/reference/routines.array-creation.html#array-creation-routines

In [ ]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full(shape=(2,2), fill_value=100)

array([[100, 100],
       [100, 100]])

In [ ]:
np.arange(start=0, stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(start=0, stop=10, num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
# Random module numpy
np.random.rand(2,5)

array([[0.04480843, 0.8411718 , 0.34746584, 0.45347759, 0.89920188],
       [0.92164354, 0.56150712, 0.52774315, 0.87031107, 0.3531193 ]])

In [ ]:
np.random.randint(low=2,high=10,size=(2,2))

array([[5, 5],
       [6, 4]])

### Array Modification Methods

In [ ]:
# reshape
x = np.ones((5,6))
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
x.reshape(2,15)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
x.T # Transpose

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x.flatten() # convert the multi dimensional array to single dimension

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
x.ravel() # convert the multi dimensional array to single dimension

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
x = np.random.randint(0,100,(3,2))

In [ ]:
x

array([[22, 80],
       [43, 66],
       [ 6,  6]])

In [ ]:
x[1,1]

66

In [ ]:
# All the values of an array to be of same data type

# Pandas Library

In [ ]:
import pandas as pd

In [ ]:
arr = np.array([[True, 1, 10.5,"hello"],[True, 1, 10.5,"hello"]])
arr

array([['True', '1', '10.5', 'hello'],
       ['True', '1', '10.5', 'hello']], dtype='<U32')

In [ ]:
# Pandas
# Each column has the same data type
# Built on top of numpy
# Series and DataFrame

### Series
![download (9).png](attachment:f91848c9-29c8-4e68-b835-12ede0b78b24.png)

In [ ]:
import pandas as pd
ser1 = pd.Series([21,20,15,14,10,15],index=["john","jacob","akshay","dheeraj","suraj","Sreedhar"], name="Age")
ser1

john        21
jacob       20
akshay      15
dheeraj     14
suraj       10
Sreedhar    15
Name: Age, dtype: int64

In [ ]:
ser1.loc['john']

21

In [ ]:
ser1.iloc[2]

15

In [ ]:
ser1.dtype

dtype('int64')

In [ ]:
ser1.index

Index(['john', 'jacob', 'akshay', 'dheeraj', 'suraj', 'Sreedhar'], dtype='object')

In [ ]:
ser1.values

array([21, 20, 15, 14, 10, 15])

In [ ]:
# Data Frame

In [ ]:
data = np.random.randint(0,100,(3,2))
data

array([[21, 75],
       [43, 34],
       [71, 76]])

In [ ]:
df = pd.DataFrame(data=data, index=['a','b','c'], columns=['x','y'])
df

x   y
a  21  75
b  43  34
c  71  76

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       3 non-null      int64
 1   y       3 non-null      int64
dtypes: int64(2)
memory usage: 72.0+ bytes


In [ ]:
df.columns

Index(['x', 'y'], dtype='object')

In [ ]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df.values

array([[21, 75],
       [43, 34],
       [71, 76]])

In [ ]:
df.loc["a","x"]

21

In [ ]:
df.iloc[2,1]

76

In [ ]:
# Load the data
df = pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [ ]:
df['Cabin']

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [ ]:
df['Cabin'].isna()

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [ ]:
df[df['Cabin'].isna()] # Boolean masking

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[687 rows x 12 columns]

In [ ]:
df['Cabin'].fillna("not available")

0      not available
1                C85
2      not available
3               C123
4      not available
           ...      
886    not available
887              B42
888    not available
889             C148
890    not available
Name: Cabin, Length: 891, dtype: object

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df['Cabin'] =  df['Cabin'].fillna("not available")

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare          Cabin Embarked  
0      0         A/5 21171   7.2500  not available        S  
1      0          PC 17599  71.2833            C85        C  
2      0  STON/O2. 3101282   7.9250  not available        S  
3      0            113803  53.1000           C123        S  
4      0            373450   8.0500  not available        S

In [ ]:
df["Sex"] == "male"

0       True
1      False
2      False
3      False
4       True
       ...  
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

In [ ]:
df[df["Sex"] == "male"]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare          Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500  not available        S  
4    35.0      0      0            373450   8.0500  not available        S  
5     NaN      0      0            330877   8.4583  not available        Q  
6    54.0      0      0             17463  51.8625            E46        S  
7     2.0      3      1            349909  21.0750  not available        S  
..    ...    ...    ...               ...      ...            ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000  not available        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500  not available        S  
886  27.0      0      0            211536  13.0000  not available        S  
889  26.0      0      0            111369  30.0000           C148        C  
890  32.0      0      0            370376   7.7500  not available        Q  

[577 rows x 12 columns]

In [ ]:
df[df["Age"] > 5]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare          Cabin Embarked  
0        0         A/5 21171   7.2500  not available        S  
1        0          PC 17599  71.2833            C85        C  
2        0  STON/O2. 3101282   7.9250  not available        S  
3        0            113803  53.1000           C123        S  
4        0            373450   8.0500  not available        S  
..     ...               ...      ...            ...      ...  
885      5            382652  29.1250  not available        Q  
886      0            211536  13.0000  not available        S  
887      0            112053  30.0000            B42        S  
889      0            111369  30.0000           C148        C  
890      0            370376   7.7500  not available        Q  

[670 rows x 12 columns]

In [ ]:
def demo_function(x):
    return x*2

In [ ]:
df["Age"].apply(demo_function)

0      44.0
1      76.0
2      52.0
3      70.0
4      70.0
       ... 
886    54.0
887    38.0
888     NaN
889    52.0
890    64.0
Name: Age, Length: 891, dtype: float64

In [ ]:
# drop
df.drop(columns=["Name"])

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0              1         0       3    male  22.0      1      0   
1              2         1       1  female  38.0      1      0   
2              3         1       3  female  26.0      0      0   
3              4         1       1  female  35.0      1      0   
4              5         0       3    male  35.0      0      0   
..           ...       ...     ...     ...   ...    ...    ...   
886          887         0       2    male  27.0      0      0   
887          888         1       1  female  19.0      0      0   
888          889         0       3  female   NaN      1      2   
889          890         1       1    male  26.0      0      0   
890          891         0       3    male  32.0      0      0   

               Ticket     Fare          Cabin Embarked  
0           A/5 21171   7.2500  not available        S  
1            PC 17599  71.2833            C85        C  
2    STON/O2. 3101282   7.9250  not available        S  
3              113803  53.1000           C123        S  
4              373450   8.0500  not available        S  
..                ...      ...            ...      ...  
886            211536  13.0000  not available        S  
887            112053  30.0000            B42        S  
888        W./C. 6607  23.4500  not available        S  
889            111369  30.0000           C148        C  
890            370376   7.7500  not available        Q  

[891 rows x 11 columns]

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare          Cabin Embarked  
0      0         A/5 21171   7.2500  not available        S  
1      0          PC 17599  71.2833            C85        C  
2      0  STON/O2. 3101282   7.9250  not available        S  
3      0            113803  53.1000           C123        S  
4      0            373450   8.0500  not available        S

In [ ]:
#select multiple columns
df[["Name","Sex"]]

Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]